version: "3.8"  # specify docker-compose version

services: # list of service containers
  postgres: 
    image: postgres # specify the image to build the container from
    restart: always # restart the container if it crashes
    ports: 
      - "5432:5432" # specify port forewarding
    environment: # environment variables
      DATABASE_HOST: 127.0.0.1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    # volumes: 
    #   - ./postgres-data:/var/lib/postgresql/data
  
  pgadmin: # GUI for postgres administration
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "jo@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports: 
      - "80:80"
    depends_on:
      - postgres # wait for the services postgres to start above before starting pgadmin